### ISSUE TITLE
Visualization Code

### ISSUE THREAD

**Issue by JayKarhade** [kabouzeid/point2vec#4]
Thank  you for open-sourcing the code ! 

I couldn't find the visualization code however. Could you share that? I couldn't completely understand how you used PCA to project it onto the point clouds, it would be great if you could shed some light into the process.

Thank you!

**Comment by LAB123-tech** [comment]
Yes, this visualization effect is great. Could you please share this code with us. Thank you very much.

**Comment by karimknaebel** [comment]
I don't think I have the visualization code anymore, it was a mess. However, it was loosely based on this: https://github.com/jiachens/ModelNet40-C/tree/master/visualize

For PCA, we computed it over all the points in a single point cloud, then mapped the top three components to the RGB channels.
